alter table public.perfiles
    add column if not exists intereses_musicales text[] not null default '{}',
    add column if not exists notificar_comentarios boolean not null default true,
    add column if not exists notificar_valoraciones boolean not null default true;

create table if not exists public.notificaciones_comunidad (
    id bigint generated by default as identity primary key,
    destinatario_id uuid not null references auth.users(id) on delete cascade,
    actor_id uuid not null references auth.users(id) on delete cascade,
    actor_nombre text not null,
    repertorio_id uuid not null references public.comunidad_repertorios(id) on delete cascade,
    tipo text not null check (tipo in ('comentario', 'valoracion')),
    resumen text,
    leida boolean not null default false,
    created_at timestamptz not null default now(),
    check (destinatario_id <> actor_id)
);

create index if not exists notificaciones_destinatario_fecha_idx
on public.notificaciones_comunidad (destinatario_id, created_at desc);
create index if not exists notificaciones_repertorio_idx
on public.notificaciones_comunidad (repertorio_id);
create unique index if not exists notificaciones_valoracion_unica_idx
on public.notificaciones_comunidad (actor_id, repertorio_id, tipo)
where tipo = 'valoracion';

alter table public.notificaciones_comunidad enable row level security;
revoke all on table public.notificaciones_comunidad from anon;
grant select, insert, update, delete on table public.notificaciones_comunidad to authenticated;
grant all on table public.notificaciones_comunidad to service_role;
grant usage, select on sequence public.notificaciones_comunidad_id_seq to authenticated, service_role;

create policy "usuarios_ven_sus_notificaciones" on public.notificaciones_comunidad
for select to authenticated using ((select auth.uid()) = destinatario_id);
create policy "usuarios_marcan_sus_notificaciones" on public.notificaciones_comunidad
for update to authenticated using ((select auth.uid()) = destinatario_id)
with check ((select auth.uid()) = destinatario_id);
create policy "usuarios_borran_sus_notificaciones" on public.notificaciones_comunidad
for delete to authenticated using ((select auth.uid()) = destinatario_id);
create policy "interacciones_crean_notificaciones_validas" on public.notificaciones_comunidad
for insert to authenticated with check (
    (select auth.uid()) = actor_id
    and destinatario_id <> actor_id
    and destinatario_id = (
        select proyecto.usuario_id from public.comunidad_repertorios proyecto
        where proyecto.id = repertorio_id
    )
);

